server:
  port: 8081
  servlet:
    context-path: /api

spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/${DB_NAME:couple-quest}?currentSchema=auth_service
    username: ${POSTGRES_USERNAME:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  liquibase:
    default-schema: auth_service
    change-log: classpath:/db/changelog/db.changelog-master.yml
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_schema: auth_service
logging:
  level:
    org.springframework.boot.autoconfigure.liquibase: DEBUG
    liquibase: INFO
    org.liquibase: INFO
jwt:
  secret: 632eca39fc29068edc74133ca9cf8f40b4942191f80c0c78dd588835beb5f57b
  access:
    expiration_minutes: 30
  refresh:
    expiration_minutes: 44640 #31 day